# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJj5j5uxUbKVOx1DXU7aj3MBUJz6AmCY

Task-2
 AUTOMATED REPORT GENERATION

task-2
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Replace with the path to your uploaded file
file_path = '/content/data.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the dataframe
df.head()

from fpdf import FPDF

# Initialize PDF
pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()

# Title
pdf.set_font('Arial', 'B', 16)
pdf.cell(200, 10, 'Employee Salary Report', ln=True, align='C')
pdf.ln(10)

# Table Header
pdf.set_font('Arial', 'B', 12)
pdf.cell(40, 10, 'Name', border=1, align='C')
pdf.cell(40, 10, 'Age', border=1, align='C')
pdf.cell(60, 10, 'Department', border=1, align='C')
pdf.cell(40, 10, 'Salary', border=1, align='C')
pdf.ln()

# Table Data
pdf.set_font('Arial', '', 12)
for index, row in df.iterrows():
    pdf.cell(40, 10, row['Name'], border=1, align='C')
    pdf.cell(40, 10, str(row['Age']), border=1, align='C')
    pdf.cell(60, 10, row['Department'], border=1, align='C')
    pdf.cell(40, 10, f"${row['Salary']:,.2f}", border=1, align='C')
    pdf.ln()

# Save PDF
pdf_output_path = '/content/employee_salary_report.pdf'
pdf.output(pdf_output_path)
print(f"Report generated successfully at {pdf_output_path}")

from google.colab import files

files.download(pdf_output_path)